### ISSUE TITLE
Officially support Develco firmware update (it already works with local .zigbee file)

### ISSUE THREAD

**Issue by galmok** [zigpy/zigpy#1265]
According to the documentation:

https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates

OTA for Develco devices isn't supported. But I just tested an update this weekend with a local .zigbee firmware file for a SmartPlug Mini and the update worked out of the box.

I did use this configuration (from the documentation) in Home Asssistant (latest release):
```
zha:
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      ikea_provider: true
      inovelli_provider: true
      ledvance_provider: true
      salus_provider: true
      sonoff_provider: true
      thirdreality_provider: true
```
Firmware update started shortly after the Plug was powered on and connected to the Coordinator (slae.sh).

What is required for a provider to make the ota feature list?
