### ISSUE TITLE
Failed to send request: Failed to enqueue message after 3 attempts: <EmberStatus.NO_BUFFERS: 24> 

### ISSUE THREAD

**Issue by marmolak** [zigpy/zigpy#1315]
I'm using Home Assistant and after upgrade to 2024.1.0, I'm no longer able to use zigbee stack.

If I want to switch device on and off, I just receive:
```
[140564133696832] Failed to send request: Failed to enqueue message after 3 attempts: <EmberStatus.NO_BUFFERS: 24>
```

And later:
```
Logger: zigpy.topology
Source: /usr/local/lib/python3.11/site-packages/zigpy/topology.py:84
First occurred: 22:32:51 (1 occurrences)
Last logged: 22:32:51

Topology scan failed
```

I'm using hacked lidl gateway with last known firmware (I can share more details if needed).

My ezsp config is:
```
ezsp_config:
        CONFIG_SOURCE_ROUTE_TABLE_SIZE: 130
        CONFIG_NEIGHBOR_TABLE_SIZE: 16
        CONFIG_MAX_END_DEVICE_CHILDREN: 6
        CONFIG_APS_UNICAST_MESSAGE_COUNT: 32
        CONFIG_BINDING_TABLE_SIZE: 32
        CONFIG_ADDRESS_TABLE_SIZE: 130
        CONFIG_ROUTE_TABLE_SIZE: 32
        CONFIG_BROADCAST_TABLE_SIZE: 32
        CONFIG_TRUST_CENTER_ADDRESS_CACHE_SIZE: 4
        CONFIG_MTORR_FLOW_CONTROL: 1
```
