### ISSUE TITLE
How to use remote_providers with home assistant and zigpy

### ISSUE THREAD

**Issue by Fredrik81** [zigpy/zigpy#1328]
Is it possible to use remote_providers with home assistant in current version of zigpy?
I see no documentation on the topic (if my searches did not file me).

The code I'm testing and I receive the following error:
voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data['ota']['remote_providers]

```
zha:
  zigpy_config:
    ota:
      ikea_provider: true                        # Auto update Trådfri devices
      inovelli_provider: true                    # Auto update INOVELLI devices
      ledvance_provider: true                    # Auto update LEDVANCE/OSRAM devices
      salus_provider: true                       # Auto update SALUS/Computime devices
      sonoff_provider: true                      # Auto update Sonoff
      thirdreality_provider: true                # Auto update 3REALITY devices
#      otau_directory: /config/zipgy_ota          # Utilize .ota files to update everything
      remote_providers:
        url: "https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/index.json"
```
