### ISSUE TITLE
RFC: Zigpy/API/Radio schemas

### ISSUE THREAD

**Issue by Adminiuga** [zigpy/zigpy#381]
ZHA integration relies on python modules providing interface to Zigbee radios/network and all those modules are using [zigpy](https://github.com/zigpy/zigpy) library for basic ZCL/ZDO interfaces and a basic `ControllerApplication`. 

With diversification of supported modules/protocols, it become problematic to have an uniform interface between ZHA and respective radio module/library, because technically ZHA is not integrating with Zigpy, but with the radio module itself. In other words `zigpy` has just a subset of configuration options a given radio module could implement. 

With that in mind in 0.20.0 we introduced schemas/configuration dict as a mean to pass parameters from ZHA integration to radio lib implementing interface with the radio. 

Most (All?) Zigpy based libraries are currently following this layout:
`zigbee.application.ControllerApplication()` <->`API()` <--> `Uart()`

The idea was to have a "configuration" dict which we could pass to `ControllerApplication()` instance and let it parse, handle and pass the required bits to the underlying layers like `API()` and `Uart/Gateway()` instances.

My idea was to allow Zigpy to define schema which affects configuration options independent of the radio being used (e.g. OTA) or options which can be implemented by all the radios (e.g. `permit()`) using zigpy. 
Radios are allowed to extend this schema and include radio specific options.

ATM, current Zigpy schema could be represented by the following `.yaml`
```yaml
database_path: /config/zigbee.db

ota:
    ikea_provider: False
    ledvance_provider: False
    otau_directory: /config/zigpy_ota

device:
    path: /dev/ttyUSB0
```

And for example [bellows](https://github.com/zigpy/bellows/) extends the above schema with the following options:
```yaml
device:
    baudrate: 57600

source_routing: False

ezsp_config:
    CONFIG_APS_UNICAST_MESSAGE_COUNT: 10
    CONFIG_ROUTE_TABLE_SIZE: 16
....
```

Making it all work with ZHA integration config entry options is going to be an interesting challenge (for @dmulcahey :) but that's another story. 
I'm open for feedback/suggestions whether it meets the current needs and/or what could be improved?

@puddly @doudz @sanyatuning @billyburly

**Comment by Adminiuga** [comment]
pasting from another repo:

Is there a reason for why the device schema is passed to both the API and the UART? There are a few configuration options that the API accesses that would essentially have to be passed from the Application to the API to get around the schema structure, which I'm "fixing" by just extending the device schema: https://github.com/zha-ng/zigpy-znp/blob/a6be2f8b2a801ee61df7871f467828d419bb9424/zigpy_znp/config.py#L25-L41

Also, will this schema be replacing the `form_network` method's arguments as well?

**Comment by puddly** [comment]
What do you think about this structure?

```yaml

# Core zigpy config
database_path: /config/zigbee.db

# Optional zigpy config
ota:
    ikea_provider: False
    ledvance_provider: False
    otau_directory: /config/zigpy_ota

# Core device config, used by all radios
device:
    path: /dev/ttyUSB0
    baudrate: 57600

    # Optional network config, used by all radios
    network:
        channels: [15, 16, 20]
        network_key: '64249a501265ba33494071bf2a72e3f1'
        pan_id: 0x1234
        extended_pan_id: 0x12345678

    # Optional radio-specific config
    ezsp_config:
        CONFIG_APS_UNICAST_MESSAGE_COUNT: 10
        CONFIG_ROUTE_TABLE_SIZE: 16
```

The top-level `device` config can then be passed to the controller application, `probe`, `new`, etc., since unused keys would be ignored.

Also, the new changes bring new `API` classmethods, like `new` and `probe`. Does the `API` (or equivalent) class have any expected structure or can it be treated as internal? If so, I think the `probe` method (and `new`?) should be moved to the controller application as well, as that can be exported by any compatible radio library as `module_name.ZIGPY_CONTROLLER_APPLICATION` (or similar), removing the need for any unnecessary hard-coding upstream.

**Comment by Adminiuga** [comment]
this is the feedback i'm looking for. To answer the 1st part, I was going by `bellows` structure and historically `bellows` configures everything from the `ControllerApplication()`  and there was no need to pass anything extra to `EZSP()` (or API() in other libs) other than the device information. 
And I didn't have the urge to pass anything extra for XBee or ConBee based modules.

But now, since you are asking, I can see how this could be useful. So how about this approach:
1. `DEVICE_SCHEMA` should keep only options required for the serial port: e.g. `path`, `baudrate`, `flow_control` and maybe for `Zigate` something like `set_pizigate_running_mode` so that doesn't have to be encoded in the port path.
2. `ControllerApplication()` should pass the entire `configuration` dict to the lower API layer and let API to pick the keys it need and pass the `device` key section down to the port. 
My preference for the radio lib to keep API layer options in its own unique key/section, e.g.
```yaml
znp_config:
    auto_reconnect: True  # would you really want this off???
    tx_power: 0
    sreq_timeout: 5
etc
```
Thus there won't be collisions between different radio libs and I'm hoping that should make things easier for ZHA


> Also, will this schema be replacing the `form_network` method's arguments as well

I was thinking about it, but left it for a later PR, however no reason to not get the feed back. 
Was thinking about `network` section (better name alternatives???) and the following params
```yaml
network:
    update_id: 1
    pan_id: 0x1234
    extended_pan_id: 00:11:22:33:44:55:66:77:88
    trust_center: 11:22:33:44:55:66:77:88:99
    mac_address: 22:33:44:55:66:77:88:99:00  # probably not all radios can change MAC?
    network_key: [1, 2, 3, 4, ... 16]
    channel_mask: 0x12345678
    channel: None
```
1. Anything else we should have here?
2. should `channel_mask` and `channel` options be mutually exclusive?
3. what options are "nice to have" and which ones are "must to have"?


```
